packages:
  - 'apps/api'
  - 'apps/ladle'
  - 'graphiql-editor'
  - 'graphiql-ui-library'
  - 'graphiql-v2'
  - 'plugins/graphiql-plugin-dialog-schema-selector'
  - 'plugins/graphiql-plugin-dialog-settings'
  - 'plugins/graphiql-plugin-operations-tools-easy-vars'
  - 'plugins/graphiql-plugin-pane-pathfinder'
  - 'plugins/graphiql-plugin-pane-history'