version: '3.6'

services: 

  mysql:
    image: mysql
    platform: linux/amd64
    restart: always
    ports: 
      - 3306:3306
    environment: 
        MYSQL_ROOT_HOST: localhost
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: db
        MYSQL_USER: user
        MYSQL_PASSWORD: user

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080