export const catBreeds = [
  { name: 'Abyssinian', subBreeds: [] },
  { name: 'Aegean', subBreeds: [] },
  { name: 'American ', subBreeds: ['Bobtail', 'Curl', 'Shorthair', 'Wirehair'] },
  { name: 'Arabian Mau', subBreeds: [] },
  { name: 'Australian Mist', subBreeds: [] },
  { name: 'Balinese', subBreeds: [] },
  { name: 'Bambino', subBreeds: [] },
  { name: 'Bengal', subBreeds: [] },
  { name: 'Birman', subBreeds: [] },
  { name: 'Bombay', subBreeds: [] },
  { name: 'British', subBreeds: ['Longhair', 'Shorthair'] },
  { name: 'Burmese', subBreeds: [] },
  { name: 'Burmilla', subBreeds: [] },
  { name: 'California Spangled', subBreeds: [] },
  { name: 'Chantilly-Tiffany', subBreeds: [] },
  { name: 'Chartreux', subBreeds: [] },
  { name: 'Chausie', subBreeds: [] },
  { name: 'Cheetoh', subBreeds: [] },
  { name: 'Colorpoint Shorthair', subBreeds: [] },
  { name: 'Cornish Rex', subBreeds: [] },
  { name: 'Cymric', subBreeds: [] },
  { name: 'Cyprus', subBreeds: [] },
  { name: 'Devon Rex', subBreeds: [] },
  { name: 'Donskoy', subBreeds: [] },
  { name: 'Dragon Li', subBreeds: [] },
  { name: 'Egyptian Mau', subBreeds: [] },
  { name: 'European Burmese', subBreeds: [] },
  { name: 'Exotic Shorthair', subBreeds: [] },
  { name: 'Havana Brown', subBreeds: [] },
  { name: 'Himalayan', subBreeds: [] },
  { name: 'Japanese Bobtail', subBreeds: [] },
  { name: 'Javanese', subBreeds: [] },
  { name: 'Khao Manee', subBreeds: [] },
  { name: 'Korat', subBreeds: [] },
  { name: 'Kurilian', subBreeds: [] },
  { name: 'LaPerm', subBreeds: [] },
  { name: 'Maine Coon', subBreeds: [] },
  { name: 'Malayan', subBreeds: [] },
  { name: 'Manx', subBreeds: [] },
  { name: 'Munchkin', subBreeds: [] },
  { name: 'Nebelung', subBreeds: [] },
  { name: 'Norwegian Forest Cat', subBreeds: [] },
  { name: 'Ocicat', subBreeds: [] },
  { name: 'Oriental', subBreeds: [] },
  { name: 'Persian', subBreeds: [] },
  { name: 'Pixie-bob', subBreeds: [] },
  { name: 'Ragamuffin', subBreeds: [] },
  { name: 'Ragdoll', subBreeds: [] },
  { name: 'Russian Blue', subBreeds: [] },
  { name: 'Savannah', subBreeds: [] },
  { name: 'Scottish Fold', subBreeds: [] },
  { name: 'Selkirk Rex', subBreeds: [] },
  { name: 'Siamese', subBreeds: [] },
  { name: 'Siberian', subBreeds: [] },
  { name: 'Singapura', subBreeds: [] },
  { name: 'Snowshoe', subBreeds: [] },
  { name: 'Somali', subBreeds: [] },
  { name: 'Sphynx', subBreeds: [] },
  { name: 'Tonkinese', subBreeds: [] },
  { name: 'Toyger', subBreeds: [] },
  { name: 'Turkish', subBreeds: ['Angora', 'Van'] },
  { name: 'York Chocolate', subBreeds: [] },
];
export const dogBreeds = [
  { name: 'affenpinscher', subBreeds: [] },
  { name: 'african', subBreeds: [] },
  { name: 'airedale', subBreeds: [] },
  { name: 'akita', subBreeds: [] },
  { name: 'appenzeller', subBreeds: [] },
  { name: 'australian', subBreeds: ['shepherd'] },
  { name: 'basenji', subBreeds: [] },
  { name: 'beagle', subBreeds: [] },
  { name: 'bluetick', subBreeds: [] },
  { name: 'borzoi', subBreeds: [] },
  { name: 'bouvier', subBreeds: [] },
  { name: 'boxer', subBreeds: [] },
  { name: 'brabancon', subBreeds: [] },
  { name: 'briard', subBreeds: [] },
  { name: 'buhund', subBreeds: ['norwegian'] },
  { name: 'bulldog', subBreeds: ['boston', 'english', 'french'] },
  { name: 'bullterrier', subBreeds: ['staffordshire'] },
  { name: 'cattledog', subBreeds: ['australian'] },
  { name: 'chihuahua', subBreeds: [] },
  { name: 'chow', subBreeds: [] },
  { name: 'clumber', subBreeds: [] },
  { name: 'cockapoo', subBreeds: [] },
  { name: 'collie', subBreeds: ['border'] },
  { name: 'coonhound', subBreeds: [] },
  { name: 'corgi', subBreeds: ['cardigan'] },
  { name: 'cotondetulear', subBreeds: [] },
  { name: 'dachshund', subBreeds: [] },
  { name: 'dalmatian', subBreeds: [] },
  { name: 'dane', subBreeds: ['great'] },
  { name: 'deerhound', subBreeds: ['scottish'] },
  { name: 'dhole', subBreeds: [] },
  { name: 'dingo', subBreeds: [] },
  { name: 'doberman', subBreeds: [] },
  { name: 'elkhound', subBreeds: ['norwegian'] },
  { name: 'entlebucher', subBreeds: [] },
  { name: 'eskimo', subBreeds: [] },
  { name: 'finnish', subBreeds: ['lapphund'] },
  { name: 'frise', subBreeds: ['bichon'] },
  { name: 'germanshepherd', subBreeds: [] },
  { name: 'greyhound', subBreeds: ['italian'] },
  { name: 'groenendael', subBreeds: [] },
  { name: 'havanese', subBreeds: [] },
  {
    name: 'hound',
    subBreeds: ['afghan', 'basset', 'blood', 'english', 'ibizan', 'plott', 'walker'],
  },
  { name: 'husky', subBreeds: [] },
  { name: 'keeshond', subBreeds: [] },
  { name: 'kelpie', subBreeds: [] },
  { name: 'komondor', subBreeds: [] },
  { name: 'kuvasz', subBreeds: [] },
  { name: 'labradoodle', subBreeds: [] },
  { name: 'labrador', subBreeds: [] },
  { name: 'leonberg', subBreeds: [] },
  { name: 'lhasa', subBreeds: [] },
  { name: 'malamute', subBreeds: [] },
  { name: 'malinois', subBreeds: [] },
  { name: 'maltese', subBreeds: [] },
  { name: 'mastiff', subBreeds: ['bull', 'english', 'tibetan'] },
  { name: 'mexicanhairless', subBreeds: [] },
  { name: 'mix', subBreeds: [] },
  { name: 'mountain', subBreeds: ['bernese', 'swiss'] },
  { name: 'newfoundland', subBreeds: [] },
  { name: 'otterhound', subBreeds: [] },
  { name: 'ovcharka', subBreeds: ['caucasian'] },
  { name: 'papillon', subBreeds: [] },
  { name: 'pekinese', subBreeds: [] },
  { name: 'pembroke', subBreeds: [] },
  { name: 'pinscher', subBreeds: ['miniature'] },
  { name: 'pitbull', subBreeds: [] },
  { name: 'pointer', subBreeds: ['german', 'germanlonghair'] },
  { name: 'pomeranian', subBreeds: [] },
  { name: 'poodle', subBreeds: ['miniature', 'standard', 'toy'] },
  { name: 'pug', subBreeds: [] },
  { name: 'puggle', subBreeds: [] },
  { name: 'pyrenees', subBreeds: [] },
  { name: 'redbone', subBreeds: [] },
  { name: 'retriever', subBreeds: ['chesapeake', 'curly', 'flatcoated', 'golden'] },
  { name: 'ridgeback', subBreeds: ['rhodesian'] },
  { name: 'rottweiler', subBreeds: [] },
  { name: 'saluki', subBreeds: [] },
  { name: 'samoyed', subBreeds: [] },
  { name: 'schipperke', subBreeds: [] },
  { name: 'schnauzer', subBreeds: ['giant', 'miniature'] },
  { name: 'setter', subBreeds: ['english', 'gordon', 'irish'] },
  { name: 'sheepdog', subBreeds: ['english', 'shetland'] },
  { name: 'shiba', subBreeds: [] },
  { name: 'shihtzu', subBreeds: [] },
  {
    name: 'spaniel',
    subBreeds: ['blenheim', 'brittany', 'cocker', 'irish', 'japanese', 'sussex', 'welsh'],
  },
  { name: 'springer', subBreeds: ['english'] },
  { name: 'stbernard', subBreeds: [] },
  {
    name: 'terrier',
    subBreeds: [
      'american',
      'australian',
      'bedlington',
      'border',
      'cairn',
      'dandie',
      'fox',
      'irish',
      'kerryblue',
      'lakeland',
      'norfolk',
      'norwich',
      'patterdale',
      'russell',
      'scottish',
      'sealyham',
      'silky',
      'tibetan',
      'toy',
      'welsh',
      'westhighland',
      'wheaten',
      'yorkshire',
    ],
  },
  { name: 'tervuren', subBreeds: [] },
  { name: 'vizsla', subBreeds: [] },
  { name: 'waterdog', subBreeds: ['spanish'] },
  { name: 'weimaraner', subBreeds: [] },
  { name: 'whippet', subBreeds: [] },
  { name: 'wolfhound', subBreeds: ['irish'] },
];
