import { hexToHSL } from './hexToHSL';

// surface1: hexToHSL({ hex: '#16171B' }),
// surface2: hexToHSL({ hex: '#222226' }),
// surface3: hexToHSL({ hex: '#363739' }),
// text1: hexToHSL({ hex: '#FFFFFF' }),
// text2: hexToHSL({ hex: '#BFBFBF' }),
// text3: hexToHSL({ hex: '#A4A4A4' }),
// text4: hexToHSL({ hex: '#55565C' }),

export const editorColors = {
  indentGuides: '#363739',
  delimiters: '#55565C',
  delimitersActive: '#A4A4A4',
  selections: '#363739',
  keywords: '#A4A4A4',
  operators: '#A4A4A4',
  text1: '#FFFFFF',
  text2: '#BFBFBF',
  text3: '#A4A4A4',
  fields: '#948AE3',
  arguments: '#FC618D',
  types: '#5AD4E6',
  values: '#7BD88F',
  orange_default: '#EE8E57',
  yellow_default: '#FCE566',
};

export const lightColors = {
  surface1: hexToHSL({ hex: '#FFFFFF' }),
  surface2: hexToHSL({ hex: '#FBFBFB' }),
  surface3: hexToHSL({ hex: '#E2E2E2' }),
  text1: hexToHSL({ hex: '#1B1B1B' }),
  text2: hexToHSL({ hex: '#606060' }),
  text3: hexToHSL({ hex: '#757575' }),
  text4: hexToHSL({ hex: '#BCBCBC' }),
  violet_default: hexToHSL({ hex: '#5C4CDD', alpha: 1 }),
  violet_light: hexToHSL({ hex: '#5C4CDD', alpha: 0.6 }),
  violet_lightest: hexToHSL({ hex: '#5C4CDD', alpha: 0.1 }),
  pink_default: hexToHSL({ hex: '#D60690', alpha: 1 }),
  pink_light: hexToHSL({ hex: '#D60690', alpha: 0.6 }),
  pink_lightest: hexToHSL({ hex: '#D60690', alpha: 0.1 }),
  blue_default: hexToHSL({ hex: '#0B6AF9', alpha: 1 }),
  blue_light: hexToHSL({ hex: '#0B6AF9', alpha: 0.6 }),
  blue_lightest: hexToHSL({ hex: '#0B6AF9', alpha: 0.1 }),
  green_default: hexToHSL({ hex: '#128934', alpha: 1 }),
  green_light: hexToHSL({ hex: '#128934', alpha: 0.6 }),
  green_lightest: hexToHSL({ hex: '#128934', alpha: 0.1 }),
  orange_default: hexToHSL({ hex: '#AF5F15', alpha: 1 }),
  orange_light: hexToHSL({ hex: '#AF5F15', alpha: 0.6 }),
  orange_lightest: hexToHSL({ hex: '#AF5F15', alpha: 0.1 }),
  yellow_default: hexToHSL({ hex: '#767800', alpha: 1 }),
  yellow_light: hexToHSL({ hex: '#767800', alpha: 0.6 }),
  yellow_lightest: hexToHSL({ hex: '#767800', alpha: 0.1 }),
  red_default: hexToHSL({ hex: '#BF0000', alpha: 1 }),
  red_light: hexToHSL({ hex: '#BF0000', alpha: 0.6 }),
  red_lightest: hexToHSL({ hex: '#BF0000', alpha: 0.1 }),
};

export const darkColors = {
  surface1: hexToHSL({ hex: '#16171B' }),
  surface2: hexToHSL({ hex: '#222226' }),
  surface3: hexToHSL({ hex: '#363739' }),
  text1: hexToHSL({ hex: '#FFFFFF' }),
  text2: hexToHSL({ hex: '#BFBFBF' }),
  text3: hexToHSL({ hex: '#A4A4A4' }),
  text4: hexToHSL({ hex: '#55565C' }),
  violet_default: hexToHSL({ hex: '#948AE3', alpha: 1 }),
  violet_light: hexToHSL({ hex: '#948AE3', alpha: 0.6 }),
  violet_lightest: hexToHSL({ hex: '#948AE3', alpha: 0.1 }),
  pink_default: hexToHSL({ hex: '#FC618D', alpha: 1 }),
  pink_light: hexToHSL({ hex: '#FC618D', alpha: 0.6 }),
  pink_lightest: hexToHSL({ hex: '#FC618D', alpha: 0.1 }),
  blue_default: hexToHSL({ hex: '#5AD4E6', alpha: 1 }),
  blue_light: hexToHSL({ hex: '#5AD4E6', alpha: 0.6 }),
  blue_lightest: hexToHSL({ hex: '#5AD4E6', alpha: 0.1 }),
  green_default: hexToHSL({ hex: '#7BD88F', alpha: 1 }),
  green_light: hexToHSL({ hex: '#7BD88F', alpha: 0.6 }),
  green_lightest: hexToHSL({ hex: '#7BD88F', alpha: 0.1 }),
  orange_default: hexToHSL({ hex: '#EE8E57', alpha: 1 }),
  orange_light: hexToHSL({ hex: '#EE8E57', alpha: 0.6 }),
  orange_lightest: hexToHSL({ hex: '#EE8E57', alpha: 0.1 }),
  yellow_default: hexToHSL({ hex: '#FCE566', alpha: 1 }),
  yellow_light: hexToHSL({ hex: '#FCE566', alpha: 0.6 }),
  yellow_lightest: hexToHSL({ hex: '#FCE566', alpha: 0.1 }),
  red_default: hexToHSL({ hex: '#FC4747', alpha: 1 }),
  red_light: hexToHSL({ hex: '#FC4747', alpha: 0.6 }),
  red_lightest: hexToHSL({ hex: '#FC4747', alpha: 0.1 }),
};
